version '1'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
    ports:
      - "5000:5000"
